#!/bin/sh

case "$1" in
  start)
    log_daemon_msg "Starting aesdsocket daemon"
    start-stop-daemon -S -n aesdsocket -x /usr/bin/aesdsocket -d
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping aesdsocket daemon"
    start-stop-daemon -K -n aesdsocket
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
